"""Adiciona campo filename à tabela Proposal

Revision ID: 0be7113a0aae
Revises: 2c43832edff2
Create Date: 2025-07-17 17:21:31.852055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be7113a0aae'
down_revision = '2c43832edff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
