"""Migração inicial limpa

Revision ID: 2c43832edff2
Revises: 
Create Date: 2025-07-17 11:06:44.638547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c43832edff2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('illustration_path', sa.String(length=256), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=64), nullable=False),
    sa.Column('nome_completo', sa.String(length=128), nullable=True),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('cnpj', sa.String(length=32), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('telefone', sa.String(length=32), nullable=True),
    sa.Column('pagamento', sa.String(length=256), nullable=True),
    sa.Column('prazo_entrega', sa.String(length=256), nullable=True),
    sa.Column('frete', sa.String(length=256), nullable=True),
    sa.Column('validade', sa.String(length=256), nullable=True),
    sa.Column('garantia', sa.String(length=256), nullable=True),
    sa.Column('garantia_sistema', sa.String(length=256), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals')
    op.drop_table('users')
    op.drop_table('equipments')
    # ### end Alembic commands ###
