"""Add servico_type and modalidade_type to Proposal

Revision ID: 3c29dcdd9497
Revises: a4b9e212b0d8
Create Date: 2025-07-24 14:08:02.806991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c29dcdd9497'
down_revision = 'a4b9e212b0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'servico_type',
            sa.Enum('PONTO', 'ACESSO', name='servicotype'),
            nullable=False,
            server_default='PONTO'      # valor padrão para tabelas existentes
        ))
        batch_op.add_column(sa.Column(
            'modalidade_type',
            sa.Enum('AQUISICAO', 'LOCACAO', name='modalidadetype'),
            nullable=False,
            server_default='AQUISICAO'  # valor padrão para tabelas existentes
        ))

    # Remover o default, deixando a coluna sem server_default
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.alter_column('servico_type', server_default=None)
        batch_op.alter_column('modalidade_type', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_column('modalidade_type')
        batch_op.drop_column('servico_type')

    # ### end Alembic commands ###
