"""Adiciona relacionamento muitos-para-muitos Proposal-Equipment

Revision ID: 57102aaf6f9c
Revises: 3c29dcdd9497
Create Date: 2025-07-29 08:13:17.389089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57102aaf6f9c'
down_revision = '3c29dcdd9497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_equipments',
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('proposal_id', 'equipment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal_equipments')
    # ### end Alembic commands ###
