"""add param_options

Revision ID: 705bae491e40
Revises: 0be7113a0aae
Create Date: 2025-07-23 14:46:08.549491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705bae491e40'
down_revision = '0be7113a0aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('param_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('PAGTO_EQUIP', 'PRAZO_ENTREGA', 'FRETE', 'VALIDADE', 'GARANTIA_EQ', 'GARANTIA_SYS', name='paramcategory'), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('param_options')
    # ### end Alembic commands ###
